name: Run test

on:
  push:
    branches:
      - "!**/feature-deploy-*"
      - "**/fixture-*"
      
  pull_request:
     branches:
       - "**/feature-deploy-*"
       - "**/fixture-*"
     types:
       - opened

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run start
