name: Run test

on:
  pull_request:
     branches:
       - "**/feature-deploy-*"
       - "!**/fixture-*"
     types:
       - opened

jobs:
  cypress-e2e-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build
          start: npm run start
