name: Pull Request in deploy branch

on:
  pull_request:
    branches:
      - "**/feature-deploy-*"
    types:
      - opened

jobs:
  pr-approved:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm run start
